// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT8ZKxEyNfm6pGbrXetxgJwW5sn5GuHUE',
    appId: '1:722272019813:web:0521cdb1286a0c334aed8c',
    messagingSenderId: '722272019813',
    projectId: 'vestiq-app',
    authDomain: 'vestiq-app.firebaseapp.com',
    storageBucket: 'vestiq-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXBqNoEhIKC5PZlPpjsV5M2OE8j6Anos',
    appId: '1:722272019813:android:9cb00b45ace10d2e4aed8c',
    messagingSenderId: '722272019813',
    projectId: 'vestiq-app',
    storageBucket: 'vestiq-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-_jWEX3GQpRgP2LMBjeqQrIkgJuQ3Hc',
    appId: '1:722272019813:ios:80060558cd32ce174aed8c',
    messagingSenderId: '722272019813',
    projectId: 'vestiq-app',
    storageBucket: 'vestiq-app.firebasestorage.app',
    iosBundleId: 'com.codernointed.vestiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf-_jWEX3GQpRgP2LMBjeqQrIkgJuQ3Hc',
    appId: '1:722272019813:ios:80060558cd32ce174aed8c',
    messagingSenderId: '722272019813',
    projectId: 'vestiq-app',
    storageBucket: 'vestiq-app.firebasestorage.app',
    iosBundleId: 'com.codernointed.vestiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT8ZKxEyNfm6pGbrXetxgJwW5sn5GuHUE',
    appId: '1:722272019813:web:9a6e77671e2701c54aed8c',
    messagingSenderId: '722272019813',
    projectId: 'vestiq-app',
    authDomain: 'vestiq-app.firebaseapp.com',
    storageBucket: 'vestiq-app.firebasestorage.app',
  );
}
